Vagrant.configure("2") do |config|
   # config.hostmanager.enabled = true 
   # config.hostmanager.manage_host = true
    
  ### gunicorn vm ###
     config.vm.define "ubuntu" do |ubuntu|
      ubuntu.vm.box = "ubuntu/trusty64"
      ubuntu.vm.box_version = "20191107.0.0"
      ubuntu.vm.hostname = "ubuntu"
      ubuntu.vm.network "public_network", bridge: "wlan0", ip: "192.168.1.200",
       use_dhcp_assigned_default_route: true
      ubuntu.vm.provider "virtualbox" do |vb|
       vb.memory = "800"
     end
     end
    end
