---
- name: update repositories
  hosts: debian
  tasks:
  - name: running sudo apt update
    ansible.builtin.apt:
      update_cache: yes
    become: yes
    
- name: Print all available facts
  hosts: debian
  tasks:
  - name: print ansible facts
    ansible.builtin.debug:
      var: ansible_facts

- name: install apache2 on debian server
  hosts: debian
  tasks:
  - name: Ensure apache is at the latest version
    ansible.builtin.apt:
      name: apache2
      state: latest
    become: true

- name: install ngnix on debian server
  hosts: debian
  tasks:
  - name: Ensure nginx is at the latest version
    ansible.builtin.apt:
      name: nginx
      state: latest
    become: true

- name: install python-gunicorn on debian server
  hosts: debian
  tasks:
  - name: Ensure python-gunicorn is installed
    ansible.builtin.apt:
      name: python3-gunicorn
      state: latest
    become: true