---
- name: Update web servers
  hosts: debian
  vars:
  tasks:
  - name: Ensure apache is at the latest version
    ansible.builtin.apt:
      name: httpd
      state: latest
    become: true

- name: Update db servers
  hosts: debian
  vars:
  tasks:
  - name: Ensure postgresql is at the latest version
    ansible.builtin.apt:
      name: postgresql
      state: latest

  - name: Ensure that postgresql is started
    ansible.builtin.service:
      name: postgresql
      state: started
    become: true