---
- name: pingtogoogle
  hosts: debian
  gather_facts: False
  #connection: local
  tasks:   
    - name: ping
      ansible.builtin.raw: ping 8.8.8.8 -c 5
    
    - name: ping test
      shell: ping -c 1 -w 2 8.8.8.8
      ignore_errors: true