---
- name: Update web servers
  hosts: centos
  vars:
    ansible_python_interpreter: /usr/bin/python3
  remote_user: centos

  tasks:
  - name: Ensure apache is at the latest version
    ansible.builtin.yum:
      name: httpd
      state: latest

- name: Update db servers
  hosts: centos
  vars:
    ansible_python_interpreter: /usr/bin/python3
  remote_user: centos

  tasks:
  - name: Ensure postgresql is at the latest version
    ansible.builtin.yum:
      name: postgresql
      state: latest

  - name: Ensure that postgresql is started
    ansible.builtin.service:
      name: postgresql
      state: started